{% set name = "click-config-file" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 1d61213ee216168e8433b9c76029f1d51694d7d9ab0f301c1ef1e4f4a65137a9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - click >=6.7
    - configobj >=5.0.6
    - python

test:
  imports:
    - click_config_file
  requires:
    - pytest
    - twine

about:
  home: http://github.com/phha/click_config_file
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Configuration file support for click applications.
  dev_url: http://github.com/phha/click_config_file

extra:
  recipe-maintainers:
    - ltalirz
    - phha
