travis:
  secure:
    BINSTAR_TOKEN: s0CgAa4MbaKGeMoT0ma3plneiu/9Nel/fgwDkR2FlZDZjfPX41Dl5eMkcxaZ9Uudgv1draG+uoFkjJJ9orqdANaPiFLXcI+BvmZxU7flrlzuJmUigMAM1SHn1SptDXaxgjEgJjApsJi3wkE9y7wkS2Injk7P23+jTSzBVkypF+G/INzYgWwKSbXlE1IsNpIfjTzwK81QsV+bNlvLIH7ib7y9U225kSu62iLVXojfZJFF9wzf+HsnZ/Wua530TyZG9XSMaLk9ALBMXsTth7kZ5tDyQ3XRPvnJICi4V3tde3FVcTuTwsoVU1bxu/hTKDcI3CRU8z1+NSZ10CaKP/1aGVYcl2wFqfgZqgZgzLrHRZLps70kOd9ofR59JbPgMzrq5PYkkLHwX34AeBrdZ1wRn1iwcT9Mx1oTmZpA/gmIIpQWbymxKm+GivGglhQzZUVWKRCBTOrqrR00ZF5WOXob7E4FsStLmwETxrCsjocTzp6chJynnt5HS9tKzC+XkTCzHXxfwFrYYh7HPpOU/qSdvl+LbQCFs5FNpGSsVFjk4LPkRzQpDYjYVPIi6hWQ1Loqb7a89677HFnh0vx0fTOT+IJTeysy5zV20mTHYZSo9N9+MM7sLVSnzKvgweQvCMXXiV0yNcOAuEqJfi5SntUH7wb+6ekAQS3hI0KqaAkjOxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
